<?php

namespace App\Notifications;

use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\URL;

/**
 * Email verification notification that points the user at the frontend SPA
 * instead of the raw backend route. The signed URL is still generated by
 * Laravel's normal mechanism (signature stays valid for the canonical
 * backend route at `verification.verify`), but the link in the email is
 * rewritten to land on the Next.js page first. The page extracts the
 * query params and proxies a GET request back to the backend's signed
 * route, which validates the signature and marks the email verified.
 *
 * This keeps verification working cross-browser (no auth middleware needed
 * on the verify route — the signature is the proof), and gives users a
 * proper editorial UI instead of a raw JSON response.
 */
class VerifyEmailNotification extends VerifyEmail
{
    /**
     * Build the verification link the user actually sees in their inbox.
     */
    protected function verificationUrl($notifiable): string
    {
        // Generate the canonical signed URL pointing at the backend route.
        // Signature is bound to this URL — the frontend will forward the
        // exact same path + query back to the backend on click.
        $backendUrl = URL::temporarySignedRoute(
            'verification.verify',
            Carbon::now()->addMinutes(Config::get('auth.verification.expire', 60)),
            [
                'id' => $notifiable->getKey(),
                'hash' => sha1($notifiable->getEmailForVerification()),
            ],
        );

        // Extract id, hash, and the signed query string (`expires`, `signature`).
        $parsed = parse_url($backendUrl);
        $query = $parsed['query'] ?? '';

        // Path is something like `/api/auth/email/verify/{id}/{hash}`.
        // Last two segments are id and hash.
        $segments = explode('/', trim($parsed['path'] ?? '', '/'));
        $hash = (string) array_pop($segments);
        $id = (string) array_pop($segments);

        $frontend = rtrim((string) Config::get('app.frontend_url'), '/');

        return $frontend.'/verify-email?'.http_build_query([
            'id' => $id,
            'hash' => $hash,
        ]).'&'.$query;
    }
}
